/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ObservationRouteImport } from './routes/observation'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PlaygroundAnimationsRouteImport } from './routes/playground.animations'
import { Route as JournalSettingsRouteImport } from './routes/journal.settings'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicReportCallbackRouteImport } from './routes/api/public/report-callback'
import { Route as AuthenticatedJournalEntriesRouteImport } from './routes/_authenticated/journal.entries'
import { Route as AuthenticatedGamesNewRouteImport } from './routes/_authenticated/games.new'
import { Route as AuthenticatedGamesGameIdRouteImport } from './routes/_authenticated/games.$gameId'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminActivityLogRouteImport } from './routes/_authenticated/admin.activity-log'
import { Route as AuthenticatedJournalEntriesIndexRouteImport } from './routes/_authenticated/journal.entries.index'
import { Route as AuthenticatedJournalEntriesIdRouteImport } from './routes/_authenticated/journal.entries.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationRoute = ObservationRouteImport.update({
  id: '/observation',
  path: '/observation',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PlaygroundAnimationsRoute = PlaygroundAnimationsRouteImport.update({
  id: '/playground/animations',
  path: '/playground/animations',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSettingsRoute = JournalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => JournalRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicReportCallbackRoute = ApiPublicReportCallbackRouteImport.update({
  id: '/api/public/report-callback',
  path: '/api/public/report-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJournalEntriesRoute =
  AuthenticatedJournalEntriesRouteImport.update({
    id: '/journal/entries',
    path: '/journal/entries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesNewRoute = AuthenticatedGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesGameIdRoute =
  AuthenticatedGamesGameIdRouteImport.update({
    id: '/games/$gameId',
    path: '/games/$gameId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityLogRoute =
  AuthenticatedAdminActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedJournalEntriesIndexRoute =
  AuthenticatedJournalEntriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedJournalEntriesRoute,
  } as any)
const AuthenticatedJournalEntriesIdRoute =
  AuthenticatedJournalEntriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedJournalEntriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/observation': typeof ObservationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/journal/settings': typeof JournalSettingsRoute
  '/playground/animations': typeof PlaygroundAnimationsRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/journal/entries': typeof AuthenticatedJournalEntriesRouteWithChildren
  '/api/public/report-callback': typeof ApiPublicReportCallbackRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/journal/entries/$id': typeof AuthenticatedJournalEntriesIdRoute
  '/journal/entries/': typeof AuthenticatedJournalEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/observation': typeof ObservationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/journal/settings': typeof JournalSettingsRoute
  '/playground/animations': typeof PlaygroundAnimationsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/games/new': typeof AuthenticatedGamesNewRoute
  '/api/public/report-callback': typeof ApiPublicReportCallbackRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/journal/entries/$id': typeof AuthenticatedJournalEntriesIdRoute
  '/journal/entries': typeof AuthenticatedJournalEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/observation': typeof ObservationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/journal/settings': typeof JournalSettingsRoute
  '/playground/animations': typeof PlaygroundAnimationsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/games/$gameId': typeof AuthenticatedGamesGameIdRoute
  '/_authenticated/games/new': typeof AuthenticatedGamesNewRoute
  '/_authenticated/journal/entries': typeof AuthenticatedJournalEntriesRouteWithChildren
  '/api/public/report-callback': typeof ApiPublicReportCallbackRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/journal/entries/$id': typeof AuthenticatedJournalEntriesIdRoute
  '/_authenticated/journal/entries/': typeof AuthenticatedJournalEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journal'
    | '/login'
    | '/mentor'
    | '/observation'
    | '/reset-password'
    | '/admin'
    | '/accept-invite/$token'
    | '/journal/settings'
    | '/playground/animations'
    | '/admin/activity-log'
    | '/admin/invites'
    | '/games/$gameId'
    | '/games/new'
    | '/journal/entries'
    | '/api/public/report-callback'
    | '/admin/'
    | '/journal/entries/$id'
    | '/journal/entries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/journal'
    | '/login'
    | '/mentor'
    | '/observation'
    | '/reset-password'
    | '/accept-invite/$token'
    | '/journal/settings'
    | '/playground/animations'
    | '/'
    | '/admin/activity-log'
    | '/admin/invites'
    | '/games/$gameId'
    | '/games/new'
    | '/api/public/report-callback'
    | '/admin'
    | '/journal/entries/$id'
    | '/journal/entries'
  id:
    | '__root__'
    | '/_authenticated'
    | '/journal'
    | '/login'
    | '/mentor'
    | '/observation'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/accept-invite/$token'
    | '/journal/settings'
    | '/playground/animations'
    | '/_authenticated/'
    | '/_authenticated/admin/activity-log'
    | '/_authenticated/admin/invites'
    | '/_authenticated/games/$gameId'
    | '/_authenticated/games/new'
    | '/_authenticated/journal/entries'
    | '/api/public/report-callback'
    | '/_authenticated/admin/'
    | '/_authenticated/journal/entries/$id'
    | '/_authenticated/journal/entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  ObservationRoute: typeof ObservationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  PlaygroundAnimationsRoute: typeof PlaygroundAnimationsRoute
  ApiPublicReportCallbackRoute: typeof ApiPublicReportCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observation': {
      id: '/observation'
      path: '/observation'
      fullPath: '/observation'
      preLoaderRoute: typeof ObservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/playground/animations': {
      id: '/playground/animations'
      path: '/playground/animations'
      fullPath: '/playground/animations'
      preLoaderRoute: typeof PlaygroundAnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/settings': {
      id: '/journal/settings'
      path: '/settings'
      fullPath: '/journal/settings'
      preLoaderRoute: typeof JournalSettingsRouteImport
      parentRoute: typeof JournalRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/report-callback': {
      id: '/api/public/report-callback'
      path: '/api/public/report-callback'
      fullPath: '/api/public/report-callback'
      preLoaderRoute: typeof ApiPublicReportCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/journal/entries': {
      id: '/_authenticated/journal/entries'
      path: '/journal/entries'
      fullPath: '/journal/entries'
      preLoaderRoute: typeof AuthenticatedJournalEntriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/new': {
      id: '/_authenticated/games/new'
      path: '/games/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof AuthenticatedGamesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/$gameId': {
      id: '/_authenticated/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthenticatedGamesGameIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity-log': {
      id: '/_authenticated/admin/activity-log'
      path: '/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/journal/entries/': {
      id: '/_authenticated/journal/entries/'
      path: '/'
      fullPath: '/journal/entries/'
      preLoaderRoute: typeof AuthenticatedJournalEntriesIndexRouteImport
      parentRoute: typeof AuthenticatedJournalEntriesRoute
    }
    '/_authenticated/journal/entries/$id': {
      id: '/_authenticated/journal/entries/$id'
      path: '/$id'
      fullPath: '/journal/entries/$id'
      preLoaderRoute: typeof AuthenticatedJournalEntriesIdRouteImport
      parentRoute: typeof AuthenticatedJournalEntriesRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityLogRoute: typeof AuthenticatedAdminActivityLogRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityLogRoute: AuthenticatedAdminActivityLogRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedJournalEntriesRouteChildren {
  AuthenticatedJournalEntriesIdRoute: typeof AuthenticatedJournalEntriesIdRoute
  AuthenticatedJournalEntriesIndexRoute: typeof AuthenticatedJournalEntriesIndexRoute
}

const AuthenticatedJournalEntriesRouteChildren: AuthenticatedJournalEntriesRouteChildren =
  {
    AuthenticatedJournalEntriesIdRoute: AuthenticatedJournalEntriesIdRoute,
    AuthenticatedJournalEntriesIndexRoute:
      AuthenticatedJournalEntriesIndexRoute,
  }

const AuthenticatedJournalEntriesRouteWithChildren =
  AuthenticatedJournalEntriesRoute._addFileChildren(
    AuthenticatedJournalEntriesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGamesGameIdRoute: typeof AuthenticatedGamesGameIdRoute
  AuthenticatedGamesNewRoute: typeof AuthenticatedGamesNewRoute
  AuthenticatedJournalEntriesRoute: typeof AuthenticatedJournalEntriesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGamesGameIdRoute: AuthenticatedGamesGameIdRoute,
  AuthenticatedGamesNewRoute: AuthenticatedGamesNewRoute,
  AuthenticatedJournalEntriesRoute:
    AuthenticatedJournalEntriesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface JournalRouteChildren {
  JournalSettingsRoute: typeof JournalSettingsRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSettingsRoute: JournalSettingsRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  ObservationRoute: ObservationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  PlaygroundAnimationsRoute: PlaygroundAnimationsRoute,
  ApiPublicReportCallbackRoute: ApiPublicReportCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
